Check that branching works:
  $ ono symbolic branching_false.wat -v
  ono: [INFO] Parsing file branching_false.wat...
  ono: [INFO] Compiling to Wasm...
  ono: [INFO] Validating...
  ono: [INFO] Linking...
  ono: [INFO] Interpreting...
  ono: [ERROR] Trap: unreachable
  {
    "labels": [],
    "model": [ { "symbol": "symbol_0", "type": "i32", "value": "1073741824" } ],
    "breadcrumbs": [ 0 ]
  }
  ono: [ERROR] owi error: Reached problem!
  [123]
  $ ono symbolic branching_true.wat -v
  ono: [INFO] Parsing file branching_true.wat...
  ono: [INFO] Compiling to Wasm...
  ono: [INFO] Validating...
  ono: [INFO] Linking...
  ono: [INFO] Interpreting...
  ono: [ERROR] Trap: unreachable
  {
    "labels": [],
    "model": [ { "symbol": "symbol_0", "type": "i32", "value": "0" } ],
    "breadcrumbs": [ 1 ]
  }
  ono: [ERROR] owi error: Reached problem!
  [123]
